spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nimatest?createDatabaseIfNotExist=true
    username: nimauser
    password: 1234

  jpa:
    show-sql: true

logging:
  level:
    org.springframework.jdbc.core: trace
    org.springframework.security: trace